[tool.poetry]
name = "metac-bot"
version = "0.1.0"
description = ""
authors = ["Vasile Popescu <elisescu@elisescu.com>"]
readme = "README.md"
package-mode = false

[tool.poetry.dependencies]
python = "^3.11"
python-decouple = "^3.8"
guidance = "^0.1.15"
openai = "^1.35.3"
llama-index-llms-openai = "^0.1.23"
llama-index = "^0.10.50"
jinja2 = "^3.1.4"
llama-index-llms-ollama = "^0.1.5"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
